### ISSUE TITLE
env TLS_SETUP_ENABLED true doesn't create a ManagementCA

### ISSUE THREAD

**Issue by chuegel** [Keyfactor/ejbca-community-helm#8]
Using the value

```
TLS_SETUP_ENABLED: "true"
```
on a fresh installation doesn't create the ManagementCA. The variable is available inside the container though:

```bash
k exec -it -n apps keyfactor-ejbca-community-helm-d9bc5dd6-lnc2t -- sh
sh-4.4$ set | grep TLS
SMTP_TLS_ENABLED=false
TLS_SETUP_ENABLED=true
```

The same happens with `TLS_SETUP_ENABLED: "simple"`

**Comment by svenska-primekey** [comment]
Have you reviewed the container logs when it started up to see what happened? Asserting simple is the default setting if this setting is not asserted.

**Comment by chuegel** [comment]
The pod seems to start normal but I have to test the deployment in our test cluster

Anyways, I created the ManagementCA manually so it's not a big deal

**Comment by chuegel** [comment]
Maybe this is the reason?

```
2024-03-22 16:06:46,175+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Configuration import automation tool is not present in this build. /opt/keyfactor/configdump/{stage.d|initialize.d}/*/*.yaml will be ignored.
```

**Comment by svenska-primekey** [comment]
> Maybe this is the reason?
> 
> ```
> 2024-03-22 16:06:46,175+0000 INFO  [/opt/keyfactor/bin/start.sh] (process:1) Configuration import automation tool is not present in this build. /opt/keyfactor/configdump/{stage.d|initialize.d}/*/*.yaml will be ignored.
> ```

No that is for configdump an enterprise feature. I think the CA is getting skipped due to providing the Initial Admin variable.

**Comment by svenska-primekey** [comment]
INITIAL_ADMIN description here: https://github.com/Keyfactor/ejbca-community-helm?tab=readme-ov-file#ejbca-environment-variables

**Comment by chuegel** [comment]
I didn't set the INITAL_ADMIN var in the chart values:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ejbca
  namespace: apps
spec:
  releaseName: keyfactor
  chart:
    spec:
      chart: ejbca-community-helm
      sourceRef:
        kind: HelmRepository
        name: ejbca
        namespace: flux-system
  interval: 60m
  values:
    replicaCount: 1
    image:
      tag: 8.2.0.1
    ejbca:
       useEphemeralH2Database: false
       env:
         TLS_SETUP_ENABLED: "true"
         METRICS_ENABLED: "true"
         OBSERVABLE_BIND: 0.0.0.0
         LOG_LEVEL_APP: INFO
         HTTPSERVER_HOSTNAME: "pki.example.com"
         SMTP_DESTINATION: "10.83.43.122"
         SMTP_PORT: '25'
         SMTP_FROM: "noreply@pki.example.com"
         SMTP_TLS_ENABLED: "false"
         SMTP_SSL_ENABLED: "false"
         DATABASE_JDBC_URL: "jdbc:postgresql://10.83.200.11:5000/ejbcadb"
       envRaw:
         - name: DATABASE_PASSWORD
           valueFrom:
             secretKeyRef:
               name: ejbca-credentials
               key: DATABASE_PASSWORD
         - name: DATABASE_USER
           valueFrom:
             secretKeyRef:
               name: ejbca-credentials
               key: DATABASE_USER
         - name: PASSWORD_ENCRYPTION_KEY
           valueFrom:
             secretKeyRef:
                name: ejbca-credentials
                key: PASSWORD_ENCRYPTION_KEY
         - name: CA_KEYSTOREPASS
           valueFrom:
             secretKeyRef:
                name: ejbca-credentials
                key: CA_KEYSTOREPASS
         - name: EJBCA_CLI_DEFAULT_PASSWORD
           valueFrom:
             secretKeyRef:
                name: ejbca-credentials
                key: EJBCA_CLI_DEFAULT_PASSWORD
         - name: APPSERVER_KEYSTORE_SECRET
           valueFrom:
             secretKeyRef:
                name: ejbca-credentials
                key: APPSERVER_KEYSTORE_SECRET
         - name: APPSERVER_TRUSTSTORE_SECRET
           valueFrom:
             secretKeyRef:
                name: ejbca-credentials
                key: APPSERVER_TRUSTSTORE_SECRET
    services:
       directHttp:
         enabled: false
       proxyAJP:
         enabled: false
         type: ClusterIP
         bindIP: 0.0.0.0
         port: 8009
       proxyHttp:
         enabled: true
         type: ClusterIP
         bindIP: 0.0.0.0
         httpPort: 8081
         httpsPort: 8082
    ingress:
       enabled: false
```

**Comment by svenska-primekey** [comment]
You have to add it to the values.yaml file, example:

```yaml
ejbca:
  env:
    INITIAL_ADMIN: "ManagementCA;CertificateAuthenticationToken:WITH_COMMONNAME;SuperAdmin"
```

**Comment by chuegel** [comment]
I understand, thanks

**Comment by ecmrauh** [comment]
Sorry for commenting a closed issue. But I have exactly the same problem. I have the settings [like shown above](https://github.com/Keyfactor/ejbca-community-helm/issues/8#issuecomment-2083506046) and I set `INITIAL_ADMIN: "ManagementCA;CertificateAuthenticationToken:WITH_COMMONNAME;SuperAdmin"`. Here are the logs:

```
INFO  [/opt/keyfactor/bin/start.sh] (process:1) Enabling HTTP proxy listeners on 0.0.0.0:8081 and 0.0.0.0:8082.
INFO  [/opt/keyfactor/bin/start.sh] (process:1) Adding initial application RoleMember ("ManagementCA;CertificateAuthenticationToken:WITH_COMMONNAME;SuperAdmin").
INFO  [org.cesecore.certificates.ca.CaSessionBean] (default task-2) CA with name ManagementCA does not exist.
ERROR [org.ejbca.ui.cli.roles.AddRoleMemberCommand] (main) No such CA 'ManagementCA'.
ERROR [/opt/keyfactor/bin/start.sh] (process:1) Failed to add initial RoleMember.
```

Is there anything I'm missing?

@chuegel Did that work for you in the end or did you create the ManagementCA manually?

**Comment by chuegel** [comment]
@ecmrauh I created the ManagementCA manually. Be sure to download the superadmin certificate in that process and change the Super Administrator Role to accept only client cert auth. For that you have to create a secret with the CA certificate (see below)
Here is my ingress (I also use a oauth2 proxy in front of the webadmin)
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: apps/managementca.crt
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header SSL_CLIENT_CERT $ssl_client_cert;
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/session-cookie-name: pki
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2.example/oauth2/start?rd=$scheme://$best_http_host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth2.example.tech/oauth2/auth
  name: ejbca-admin-ingress
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
  - host: pki.example.tech
    http:
      paths:
      - backend:
          service:
            name: keyfactor-ejbca-community-helm
            port:
              number: 8082
        path: /ejbca
        pathType: Prefix
  tls:
  - hosts:
    - pki.example.tech
    secretName: pki-example-cert
```
